version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.11
    ports:
      - 5432:5432
    networks:
      postgres-net:
        ipv4_address: 172.28.0.2

networks:
  postgres-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

